title: Pedro Cintra
subtitle: That's me!
logo: /assets/img/Me_folha_crop.png
bio: MsC in Physics and Science Communicator. Passionate about science, cooking and Legos.
description: Welcome to my website!
email: pedrohpc96@hotmail.com
twitter: "@pedrocintra52"
github: PedroHPCintra
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

plugins:
  - jemoji