title: Pedro Cintra
subtitle: "That's me :v::kissing:"
logo: /assets/img/Me_folha_crop.png
# image: /assets/img/Lotka-Volterra_art.png
bio: MsC in Physics and Science Communicator. passionate about science, cooking and Legos.
description: Welcome to my website!
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman