title: Pedro Cintra
subtitle: That's me!
logo: /assets/img/Me_folha_crop.png
bio: MsC in Physics and Science Communicator. passionate about science, cooking and Legos.
description: Welcome to my website!
# intro: Bem vindo(a/e) ao meu site! Aqui você encontrará informações sobre meus projetos de pesquisa, minha carreira acadêmica, publicações e alguns detalhes pessoais, como minha paixão por fotos de Legos e meus canais do YouTube favoritos. Se você é um aluno de graduação, eu preparei uma [página](./another-page.md) com várias recomendações para a sua graduação em Física.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman